spring.application.name=PyTutor

spring.datasource.url=jdbc:postgresql://localhost:5432/pytutor
spring.datasource.username=pytutor_user
spring.datasource.password=pytutor123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080
server.servlet.context-path=/api